/* When the marketing pages' content last changed. Drives sitemap lastmod —
   move it whenever page copy changes, so crawlers re-read what changed. */
export const contentUpdatedAt = "2026-09-28";

export const workflow = [
  "Intake",
  "Documents",
  "Financials",
  "Verification",
  "Fraud",
  "Policy",
  "Report",
  "Human Decision",
];

const productPages = [
  {
    path: "product/document-intelligence",
    group: "Product",
    name: "Document Intelligence",
    title: "What did the borrower actually send?",
    description: "Classify every submitted file, extract the fields underwriting depends on, and keep each value linked to the page and line it came from — before anyone starts the analysis.",
    metaTitle: "Document Intelligence for Loan Underwriting",
    metaDescription: "Classify, extract and structure borrower documents into source-linked underwriting data, so MCA and alternative lending teams review each file faster.",
    keywords: ["document intelligence for lenders", "loan document extraction", "underwriting document automation", "MCA document review", "source-linked data extraction"],
    points: ["Classify and organize submitted files", "Extract decision-relevant fields", "Keep analysis connected to source material"],
  },
  {
    path: "product/bank-statement-analysis",
    group: "Product",
    name: "Bank Statement Analysis",
    title: "What does the bank activity really say?",
    description: "See deposits, revenue behaviour, balances, negative days, NSFs and cash-flow movement across the statement period — without reconstructing it line by line.",
    metaTitle: "Bank Statement Analysis Software for Lenders",
    metaDescription: "Analyze deposits, daily balances, NSFs, negative days and existing MCA positions across bank statements, with every figure linked to its source line.",
    keywords: ["bank statement analysis software", "cash flow underwriting", "average daily balance analysis", "NSF and negative day detection", "MCA position detection"],
    points: ["Structure statement activity", "Surface cash-flow patterns for review", "Give underwriters evidence for follow-up"],
  },
  {
    path: "product/business-verification",
    group: "Product",
    name: "Business Verification",
    title: "Who are we actually funding?",
    description: "Compare the legal entity, business details, ownership, address and application claims against verification evidence before treating the rest of the file as fact.",
    metaTitle: "Business Verification (KYB) Software for Lenders",
    metaDescription: "Compare legal entity, ownership, address and application claims against verification sources, with every conflict held open for underwriter review.",
    keywords: ["business verification software", "KYB for lenders", "know your business verification", "KYB and KYC underwriting", "business identity verification"],
    points: ["Organize verification findings", "Highlight conflicts for human review", "Preserve sources and reviewer notes"],
  },
  {
    path: "product/fraud-signals",
    group: "Product",
    name: "Fraud Signals",
    title: "Does the borrower package actually hold together?",
    description: "Catch missing or duplicate documents, conflicting names and numbers, suspicious document signals and inconsistencies between what was submitted and what the evidence shows.",
    metaTitle: "Fraud Signals for Small Business Lending",
    metaDescription: "Surface document tampering signs, conflicting details, duplicate files and transaction inconsistencies in MCA and SMB files, for human review rather than auto-decline.",
    keywords: ["fraud signals lending", "small business lending fraud detection", "MCA fraud detection", "bank statement fraud detection", "document fraud detection"],
    points: ["Flag inconsistencies and unusual patterns", "Separate signals from final decisions", "Keep evidence available to reviewers"],
  },
  {
    path: "product/policy-engine",
    group: "Product",
    name: "Policy Engine",
    title: "Where does the deal fall outside our rules?",
    description: "Evaluate the file against your lender-defined thresholds, conditions and exceptions so the team can see exactly what passed, what failed and what needs judgment.",
    metaTitle: "Loan Policy Engine for Alternative Lenders",
    metaDescription: "Evaluate each deal against your own credit policy — thresholds, conditions and exceptions — with results tied to evidence and documented overrides.",
    keywords: ["loan policy engine", "credit policy engine", "underwriting rules engine", "lender credit policy automation", "policy exceptions and overrides"],
    points: ["Apply lender-specific review criteria", "Show policy outcomes with context", "Support documented human overrides"],
  },
  {
    path: "product/underwriting-report",
    group: "Product",
    name: "Underwriting Report",
    title: "What still needs an underwriter to decide?",
    description: "Bring unresolved conflicts, policy exceptions, risk signals and reviewer notes into one place so the remaining judgment is clear instead of buried across the file.",
    metaTitle: "Evidence-Linked Underwriting Reports & Deal Memos",
    metaDescription: "Assemble financials, verification, fraud signals and policy results into one evidence-linked underwriting report, with open items left for the underwriter.",
    keywords: ["underwriting report software", "evidence-linked underwriting", "underwriting deal memo", "loan decision documentation", "underwriting audit trail"],
    points: ["Summarize the complete deal", "Link findings to supporting evidence", "Record reviewer notes and decisions"],
  },
];

const solutionPages = [
  {
    path: "solutions/merchant-cash-advance",
    group: "Solutions",
    name: "Merchant Cash Advance",
    title: "Underwrite the whole MCA file - not just the bank statement.",
    description: "Cevrynt brings borrower documents, cash-flow analysis, existing MCA positions, business verification, fraud review, and your lender policy into one evidence-linked underwriting review.",
    metaTitle: "Merchant Cash Advance (MCA) Underwriting Software",
    metaDescription: "MCA underwriting software that brings bank statements, existing positions, verification, fraud signals and your policy into one evidence-linked review.",
    keywords: ["merchant cash advance underwriting software", "MCA underwriting automation", "MCA underwriting", "MCA stacking detection", "MCA bank statement analysis"],
    points: ["Read bank activity without rebuilding it in a spreadsheet", "Surface revenue patterns, negative days and existing positions", "Apply your own policy without hiding exceptions", "Keep the evidence behind the final underwriter call"],
  },
  {
    path: "solutions/alternative-lenders",
    group: "Solutions",
    name: "Alternative Lenders",
    title: "Underwrite the SMB file without losing the story behind it.",
    description: "Cevrynt brings borrower documents, bank activity, business verification, fraud signals, and your credit policy into one evidence-linked review — with exceptions left visible for your underwriters.",
    metaTitle: "Underwriting Software for Alternative Lenders",
    metaDescription: "One connected underwriting workflow for SMB and revenue-based finance teams: documents, bank activity, verification, fraud signals and credit policy.",
    keywords: ["alternative lending software", "SMB underwriting software", "revenue-based financing underwriting", "small business lending underwriting", "alternative lender underwriting workflow"],
    points: ["Create a repeatable review path", "Keep evidence and exceptions visible", "Support credit, risk, and operations teams"],
  },
  {
    path: "solutions/brokers-isos",
    group: "Solutions",
    name: "Brokers and ISOs",
    title: "Know what the lender will find before you send the file.",
    description: "Cevrynt reviews the borrower package, bank activity, existing obligations, business verification, and missing or conflicting information — so your team can send a cleaner submission with fewer surprises downstream.",
    metaTitle: "Submission Tools for MCA Brokers & ISOs",
    metaDescription: "Help brokers and ISOs catch missing documents, conflicting details and existing positions before a file reaches the lender, so submissions arrive cleaner.",
    keywords: ["MCA broker software", "ISO submission software", "broker underwriting tools", "MCA deal submission", "ISO file preparation"],
    points: ["Organize submission packages", "Identify incomplete borrower information", "Support clearer lender handoffs"],
  },
  {
    path: "solutions/ecommerce-merchant-underwriting",
    group: "Solutions",
    name: "E-commerce Merchant Underwriting",
    title: "Underwrite the merchant behind the storefront.",
    description: "Cevrynt brings commerce performance, borrower documents, bank activity, business verification, existing obligations, and lender policy into one evidence-linked review — so platform signals become part of the underwriting decision, not a substitute for it.",
    metaTitle: "E-commerce Merchant Underwriting Software",
    metaDescription: "Underwrite e-commerce and marketplace merchants with commerce performance, bank activity, verification and lender policy in one evidence-linked review.",
    keywords: ["e-commerce merchant underwriting", "Shopify merchant underwriting", "marketplace seller financing", "e-commerce merchant cash advance", "commerce data underwriting"],
    points: ["Structure merchant underwriting inputs", "Combine documentary and business context", "Keep lender control at the final decision"],
  },
];

const corePages = [
  {
    path: "platform",
    group: "Platform",
    name: "Platform",
    title: "Every answer, tied back to the file.",
    description: "Documents, bank analysis, verification, fraud signals, lender policy, and underwriting memos in one evidence-linked workflow.",
    metaTitle: "AI Underwriting Platform for Alternative Lenders",
    metaDescription: "One evidence-linked underwriting workflow — intake, document extraction, bank statement analysis, KYB, fraud signals and lender policy. The final call stays yours.",
    keywords: ["AI underwriting platform", "underwriting workflow software", "decision intelligence for lending", "AI underwriting software", "MCA underwriting platform"],
    points: ["Move from intake to evidence-backed report", "Keep sources, notes, and overrides together", "Support—not replace—human underwriting"],
  },
  {
    path: "why-cevrynt",
    group: "Why Cevrynt",
    name: "Why Cevrynt",
    title: "Your underwriting rules. Your evidence. Your final call.",
    description: "Cevrynt prepares the review around lender-defined policy and source-linked evidence, while exceptions and final funding decisions stay with your team.",
    absoluteTitle: "Why Cevrynt — Explainable AI Underwriting for Lenders",
    metaTitle: "Why Cevrynt | Explainable AI Underwriting for Lenders",
    metaDescription: "Explainable, evidence-linked AI underwriting that applies your lender policy, keeps exceptions visible and leaves final credit decisions with your underwriters.",
    keywords: ["explainable AI underwriting", "human in the loop underwriting", "evidence-linked underwriting", "AI underwriting for lenders"],
    points: ["Reduce fragmented review work", "Preserve lender-specific judgment", "Make findings easier to inspect and explain"],
  },
  {
    path: "integrations",
    group: "Platform",
    name: "Integrations",
    title: "Keep your stack. Connect Cevrynt around it.",
    description: "Cevrynt is designed to fit around the systems already moving your deals — intake, LOS or CRM, document sources, verification providers, and downstream reporting.",
    metaTitle: "Underwriting Workflow Integrations for Lenders",
    metaDescription: "Plan how Cevrynt fits around your intake, LOS or CRM, document sources and verification providers, with integration requirements scoped before a pilot.",
    keywords: ["lending software integrations", "underwriting workflow integration", "LOS integration underwriting", "CRM integration lending"],
    points: ["Map intake and document sources", "Define controlled workflow handoffs", "Evaluate integrations during a qualified walkthrough"],
  },
  {
    path: "security",
    group: "Trust",
    name: "Security",
    title: "Sensitive underwriting data deserves deliberate boundaries.",
    description: "Cevrynt is designed around scoped access, controlled data handling, traceable activity, and lender-defined retention requirements — so security can be agreed around the underwriting workflow before production use.",
    metaTitle: "Security & Data Handling for Underwriting Teams",
    metaDescription: "How Cevrynt approaches scoped access, controlled data handling, audit trails and lender-defined retention for sensitive borrower underwriting data.",
    keywords: ["underwriting data security", "lending software security", "borrower data handling", "underwriting audit trail"],
    points: ["Review access and data-flow requirements", "Plan auditability and reviewer accountability", "Validate requirements before a pilot"],
  },
  {
    path: "pilot",
    group: "Pilot",
    name: "Pilot",
    title: "Design a focused underwriting pilot",
    description: "Work with the Cevrynt team to define a narrow workflow, representative files, review criteria, and clear evaluation goals.",
    metaTitle: "Underwriting Pilot for MCA & Alternative Lenders",
    metaDescription: "Scope a focused underwriting pilot with Cevrynt: a narrow workflow, representative files, clear review criteria and agreed evaluation goals.",
    keywords: ["underwriting software pilot", "MCA underwriting pilot", "AI underwriting pilot", "alternative lending software trial"],
    points: ["Choose a bounded use case", "Align on lender-specific review needs", "Keep human approval authority explicit"],
    cta: "Discuss a pilot",
  },
];

const partnerPages = [
  {
    path: "partners/shopline",
    group: "Partner",
    name: "Cevrynt × SHOPLINE",
    title: "Cevrynt × SHOPLINE",
    description: "A documented development and referral partnership around e-commerce merchant-underwriting workflows.",
    absoluteTitle: "Cevrynt × SHOPLINE — E-commerce Underwriting Partnership",
    metaTitle: "Cevrynt × SHOPLINE Partnership",
    metaDescription: "A documented development and referral partnership exploring e-commerce merchant-underwriting workflows between Cevrynt and SHOPLINE.",
    keywords: ["Cevrynt SHOPLINE partnership", "e-commerce underwriting partnership", "SHOPLINE merchant financing"],
    points: ["Explore relevant merchant-underwriting workflows", "Coordinate development and qualified referrals", "Keep lender eligibility and decisions independent"],
    notice: "This partnership does not imply a generally available live integration, automatic data sharing, universal merchant eligibility, or guaranteed funding.",
  },
];

const companyPages = [
  {
    path: "about",
    group: "Company",
    name: "About",
    title: "Building the evidence layer for modern underwriting.",
    description: "Cevrynt turns fragmented deal files — applications, bank statements, business verification, risk signals, and lender policy — into a structured, source-linked underwriting review. We help MCA and alternative lending teams move faster without hiding exceptions or taking the final credit decision away from the lender.",
    absoluteTitle: "About Cevrynt — AI Underwriting Infrastructure for Lenders",
    metaTitle: "About Cevrynt | AI Underwriting Infrastructure",
    metaDescription: "Cevrynt, Inc. builds AI-assisted underwriting infrastructure for MCA and alternative lenders: evidence-linked, explainable and built around human decisions.",
    keywords: ["about Cevrynt", "Cevrynt, Inc.", "AI underwriting infrastructure company", "underwriting software company"],
    points: ["Built around real underwriting workflows", "Focused on evidence and explainability", "Designed with human decision control"],
  },
  {
    path: "investors",
    group: "Company",
    name: "Investors",
    title: "Small-business lending moves fast. Underwriting still does not.",
    description: "Cevrynt, Inc. turns a messy borrower package into an evidence-backed, policy-aware underwriting review a lender can inspect and act on. We are raising a $250K pre-seed round to take the working MVP to a lender-ready launch.",
    absoluteTitle: "Invest in Cevrynt — $250K Pre-Seed, AI Underwriting Infrastructure",
    metaTitle: "Investors: $250K Pre-Seed for AI Underwriting Infrastructure",
    metaDescription: "Cevrynt is raising a $250K pre-seed round. Working MVP, 200+ real-world underwriting files evaluated, a signed SHOPLINE referral agreement and a clear 18-month plan. Book an investor meeting.",
    keywords: ["Cevrynt investors", "Cevrynt pre-seed", "AI underwriting startup", "fintech pre-seed round", "alternative lending infrastructure", "MCA underwriting startup"],
    points: ["Raising a $250K pre-seed", "Working MVP evaluated on 200+ real-world files", "Pitch deck shared after a meeting or by email"],
    cta: "Book an investor meeting",
    ctaHref: "https://calendly.com/arin-cevrynt/cevrynt-demo",
  },
  {
    path: "contact",
    group: "Company",
    name: "Contact",
    title: "Bring the file, workflow, or opportunity.",
    description: "Whether you are evaluating Cevrynt for underwriting, exploring a lender or platform workflow, discussing a partnership, or looking at the company as an investor, start directly with the team building it.",
    absoluteTitle: "Contact Cevrynt — Book an Underwriting Walkthrough",
    metaTitle: "Contact Cevrynt | Book a Walkthrough",
    metaDescription: "Book a walkthrough of Cevrynt or email sales@cevrynt.com about underwriting workflows, pilots, partnerships or investment.",
    keywords: ["contact Cevrynt", "book underwriting software demo", "AI underwriting demo", "MCA underwriting software demo"],
    points: ["Sales enquiries: sales@cevrynt.com", "Investor enquiries: arin@cevrynt.com", "Qualified walkthroughs via Calendly"],
  },
];

const resourcePages = [
  {
    path: "compare",
    group: "Resources",
    name: "Compare",
    title: "How Cevrynt compares with other AI underwriting tools",
    description: "An honest map of the AI underwriting market for MCA funders and alternative lenders — Kaaj, Heron, Ocrolus, MoneyThumb and MCA platforms — and where Cevrynt fits.",
    absoluteTitle: "AI Underwriting Software Compared: Kaaj, Heron, Ocrolus & Cevrynt",
    metaDescription: "Comparing AI underwriting software for MCA and alternative lenders: Kaaj, Heron, Ocrolus, MoneyThumb and MCA CRMs vs Cevrynt — what each does and who it fits.",
    keywords: ["Kaaj alternative", "Kaaj vs Cevrynt", "Heron Data alternative", "Ocrolus alternative", "MoneyThumb alternative", "AI underwriting software comparison", "best MCA underwriting software", "MCA underwriting tools"],
    points: ["Four categories of AI underwriting tools", "Where Cevrynt fits and where it does not", "Questions to ask any vendor"],
  },
  {
    path: "resources",
    group: "Resources",
    name: "Resources",
    title: "Underwriting resources",
    description: "Practical perspectives on document review, financial analysis, fraud signals, policy evaluation, and explainable decisions.",
    metaTitle: "Underwriting Resources for Alternative Lenders",
    metaDescription: "Guides and perspectives on document review, financial analysis, fraud signals, policy evaluation, and explainable underwriting decisions.",
    keywords: ["underwriting resources", "alternative lending guides", "MCA underwriting guides", "underwriting glossary"],
    points: ["Underwriting workflow guides", "Product and policy perspectives", "Evidence-focused operating practices"],
  },
];

const legalPages = [
  {
    path: "privacy",
    group: "Legal",
    name: "Privacy Policy",
    title: "Privacy Policy",
    description: "How Cevrynt, Inc. collects, uses, shares and protects personal information through its website, and how borrower data processed for lenders is handled.",
    keywords: ["Cevrynt privacy policy", "underwriting data privacy"],
    legal: true,
  },
  {
    path: "terms",
    group: "Legal",
    name: "Terms of Use",
    title: "Terms of Use",
    description: "The terms that govern access to and use of the Cevrynt website, including acceptable use, intellectual property, disclaimers and limits of liability.",
    keywords: ["Cevrynt terms of use", "Cevrynt website terms"],
    legal: true,
  },
  {
    path: "cookie-policy",
    group: "Legal",
    name: "Cookie Policy",
    title: "Cookie Policy",
    description: "The Google Analytics cookies and browser storage the Cevrynt website uses, how consent works and how to change your choice. No advertising or tracking cookies.",
    keywords: ["Cevrynt cookie policy", "Cevrynt browser storage"],
    legal: true,
  },
];

export const sitePages = [
  ...corePages,
  ...productPages,
  ...solutionPages,
  ...partnerPages,
  ...companyPages,
  ...resourcePages,
  ...legalPages,
];

export const pageByPath = new Map(sitePages.map((page) => [page.path, page]));

export const navGroups = [
  {
    label: "Platform",
    href: "/platform",
    items: [
      ["Platform overview", "/platform"],
      ["Why Cevrynt", "/why-cevrynt"],
      ["Integrations", "/integrations"],
      ["Security", "/security"],
    ],
  },
  {
    label: "Product",
    items: productPages.map((page) => [page.name, `/${page.path}`]),
  },
  {
    label: "Solutions",
    items: solutionPages.map((page) => [page.name, `/${page.path}`]),
  },
  {
    label: "Partners",
    href: "/partners/shopline",
  },
  {
    label: "Company",
    items: companyPages.map((page) => [page.name, `/${page.path}`]),
  },
  {
    label: "Resources",
    items: [
      ["Resources", "/resources"],
      ["Compare", "/compare"],
      ["Blog", "/blog"],
      ["FAQ", "/faq"],
    ],
  },
];
